spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/bootReact?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    propertise:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.habernate.SQL: debug
#  org.hibernate.type: trace